name: Build Vintage Story Docker image

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: "Release type"
        required: true
        default: "stable"
        type: choice
        options:
          - stable
          - unstable
          - pre
      version:
        description: "Game version MAJOR.MINOR.PATCH"
        required: true
      minor_version:
        description: "Game version MAJOR.MINOR (only stable version)"
        required: false

jobs:
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push (stable)
        if: ${{ github.event.inputs.release_type == 'stable' }}
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          build-args: |
            RELEASE_TYPE=${{ github.event.inputs.release_type }}
            VERSION=${{ github.event.inputs.version }}
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/vintagestory:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/vintagestory:${{ github.event.inputs.release_type }}
            ${{ secrets.DOCKER_HUB_USERNAME }}/vintagestory:${{ github.event.inputs.minor_version }}
            ${{ secrets.DOCKER_HUB_USERNAME }}/vintagestory:${{ github.event.inputs.version }}

      - name: Build and push (unstable)
        if: ${{ github.event.inputs.release_type == 'unstable' }}
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          build-args: |
            RELEASE_TYPE=${{ github.event.inputs.release_type }}
            VERSION=${{ github.event.inputs.version }}
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/vintagestory:${{ github.event.inputs.release_type }}
            ${{ secrets.DOCKER_HUB_USERNAME }}/vintagestory:${{ github.event.inputs.version }}

      - name: Build and push (pre)
        if: ${{ github.event.inputs.release_type == 'pre' }}
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          build-args: |
            RELEASE_TYPE=${{ github.event.inputs.release_type }}
            VERSION=${{ github.event.inputs.version }}
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/vintagestory:unstable
            ${{ secrets.DOCKER_HUB_USERNAME }}/vintagestory:${{ github.event.inputs.version }}
